(function () {
    window.state = {
        RED_NUMS: [1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36],
        PERIMETER_RULE_KEY: 'Perimeter Rule',
        PREDICTION_PERIMETER_PATTERN: 'Prediction Perimeter',
        AI_TAKEOVER_PATTERN: 'AI Takeover',
        ENGINE_PRIMARY_WINDOW: 14,
        ENGINE_CONFIRMATION_WINDOW: 5,
        HUD_RECENT_WINDOW: 14,
        GEMINI_MODEL: 'gemini-2.5-flash',
        AI_RELAY_BASE_URL: 'http://127.0.0.1:8787/api/ai',
        AI_RELAY_SENTINEL: '__inside_tool_secure_relay__',
        INTELLIGENCE_VIEW_KEY: 'insideTool.intelligenceViewMode',
        INTELLIGENCE_VIEWS: ['brief', 'diagnostic', 'minimal'],
        RACETRACK_ORDER: [0, 32, 15, 19, 4, 21, 2, 25, 17, 34, 6, 27, 13, 36, 11, 30, 8, 23, 10, 5, 24, 16, 33, 1, 20, 14, 31, 9, 22, 18, 29, 7, 28, 12, 35, 3, 26],
        BULK_REPLAY_CHUNK_SIZE: 24,
        HISTORY_RENDER_CHUNK_SIZE: 80,

        currentInputLayout: 'grid', // 'grid' or 'racetrack'
        history: [],
        activeBets: [],
        globalSpinIdCounter: 0,
        spinProcessingQueue: Promise.resolve(),
        faceGaps: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
        predictionPerimeterWindow: 14,
        perimeterRuleEnabled: true,
        advancementLog: [],
        chatMessageHistory: [],
        aiEnabled: false,
        aiProvider: 'gemini',
        aiApiKey: '',
        neuralPredictionEnabled: false,
        currentNeuralSignal: null,
        neuralPredictionRequestId: 0,
        aiSignalLedger: [],
        lastAiFusionSnapshot: null,
        aiPredictionCacheKey: '',
        aiPredictionCacheSignal: null,
        aiPredictionInFlight: null,
        aiApiKeyVisible: false,
        aiRelayAvailable: false,
        aiRuntimeState: {
            status: 'IDLE',
            provider: 'gemini',
            lastError: '',
            lastRequestMode: '',
            lastLatencyMs: 0,
            lastPromptPreview: '',
            lastResponsePreview: '',
            lastUpdatedLabel: 'Never'
        },
        patternConfig: {},
        userStats: {
            totalWins: 0, totalLosses: 0, netUnits: 0,
            bankrollHistory: [0],
            betLog: []
        },
        currentPredictionStrategy: 'series',
        currentGameplayStrategy: 'series', // 'series' or 'combo'
        strategies: {},
        changeStrategyTimeout: null,
        cachedAddSpinBtn: null,
        perimeterStatsCache: {},
        currentAnalyticsTab: 'strategy',
        currentIntelligenceMode: 'brief',
        isHudColdMode: false,
        hudHistoryScope: 'all',
        engineSnapshot: null,
        lastActionableComboLabel: null,
        lastActionableTargetFace: null,
        lastActionableCheckpointSpin: 0,
        analyticsDisplayStrategy: 'series',
        historyRenderVersion: 0,
        strategySyncCache: { series: null, combo: null }
    };
    window.currentAlerts = [];
})();
